sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.java.coveragePlugin=jacoco
sonar.coverage.exclusions=\
src/main/java/com/innowise/userservice/dto/**,\
src/main/java/com/innowise/userservice/entity/**,\
src/main/java/com/innowise/userservice/exception/**,\
src/main/java/com/innowise/userservice/configuration/**