spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: docker
  application:
    name: user-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true