spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  cache:
    type: none
jwt:
  secret: ${JWT_SECRET:com-innowise-authentication-service-secret-key}
logging:
  level:
    root: INFO
    org.springframework: DEBUG